[package]
name = "share-preview"
version = "0.1.2"
authors = ["Rafael Mardojai CM <email@rafaelmardojai.com>"]
edition = "2018"

[dependencies]
adw = { version = "0.1.0-alpha-6", package = "libadwaita" }
image = "0.23"
log = "0.4"
pretty_env_logger = "0.4"
gettext-rs = { version = "0.6", features = ["gettext-system"] }
gtk = { version = "0.3.1", package = "gtk4" }
gtk-macros = "0.3"
once_cell = "1.5"
url = "2.2"
uuid = { version = "0.8", features = ["serde", "v4"] }
scraper = "0.12"
surf = "2.2"
