on:
  push:
    branches: [master]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-20.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: "share-preview-devel.flatpak"
        manifest-path: "build-aux/com.rafaelmardojai.SharePreview.Devel.json"
        run-tests: "true"
        cache-key: flatpak-builder-${{ github.sha }}
